[project]
name = "ta-cloudflare-logs"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "requests==2.32.5",
    "solnlib>=6.3",
    "splunk-sdk>=2,<3",
    "splunktaucclib>=8.2,<9",
]

[dependency-groups]
dev = [
    "pip>=26.0.1",
    "pytest>=8.4.2",
    "ruff>=0.16.10",
    "splunk-add-on-ucc-framework==6.6.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "B"]
